import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/layouts/Header/Header";
import Footer from "../../layouts/footer/Footer";
import ItemsContainer from "@/pages/components/ItemsContainer";
import axios from "axios";
import { useState } from "react";
import useGenre from "@/hooks/[gener]";
import React, { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

interface Props {
  items: [] ;
  page :number ;
  pages:number ;
  geners :[];
}

export default function Home(props: Props) {
  const [content, setContent] = useState([]);

  const [genres, setGenres] = useState([]);
  const [selectedGenres, setSelectedGenres] = useState([]);

  const [pageno, setPageno] = useState(1)
  const [paginationno, setPaginationno] = useState(0)
  

  
  const genreforURL = useGenre(selectedGenres)

  const GetDataTrending = async ()=>{
      
      const {data} = await axios.get(`https://api.themoviedb.org/3/discover/movie?api_key=c76f21405a6fbe2e74354773617a04b8&page=${pageno}&with_genres=&language=en-US&
      with_genres=${genreforURL}`)
      setContent(data.results);
      setPageno(data.page)
      setPaginationno(data.total_pages);
      console.log('data.results', data)
  }

  useEffect(()=>{
      console.log('Trending Component did mount');
      GetDataTrending();
      

      //eslint-disable-next-line
  }, [])

  useEffect(()=>{
      GetDataTrending();
      //eslint-disable-next-line
  }, [pageno, genreforURL])

  const handleClick = (number :any)=>{
      setPageno(number);
  }
  useEffect(()=>{
      console.log('Trending Component didupdate mount');
      GetDataTrending();
      //eslint-disable-next-line
  }, [pageno])
  // console.log(selectedGenres);

  return (
    <>
      <Head>
        <title>Tv App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ItemsContainer items={content} page={pageno} pages={paginationno} gener={genreforURL}      />
      <Footer />
    </>
  );
}

