import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/layouts/Header/Header";
import MainContainer from "@/pages/components/MainContainer";
import Footer from "../layouts/footer/Footer";
import ItemsContainer from "@/pages/components/ItemsContainer";
import { BrowserRouter } from "react-router-dom";
import { GetServerSideProps } from "next";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  items: [];
}

export default function Home(props: Props) {
  const {items} = props
  return (
    <>
      <Head>
        <title>Tv App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainContainer />
      <ItemsContainer items={items} />
      <Footer />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const {} = context;
  const { data: res } = await axios.get(
    `https://api.themoviedb.org/3/trending/movie/day?api_key=c76f21405a6fbe2e74354773617a04b8`
  );

  console.log("data :>>", res);
  return {
    props: {
      items: await res.results,
    },
  };
};
